server {
  listen 80;
  server_name localhost;
  index index.html;
  client_max_body_size 20M;

  location /api/ {
    proxy_pass http://backend:8000/api/;
    proxy_set_header Host $host;
  }
  
  location /admin/ {
    proxy_pass http://backend:8000/admin/;
    proxy_set_header Host $host;
  }
  
  location /media/ {
    alias /media/;
  }

  # Статика бэкенда (admin, rest_framework)
  location /static/admin/ {
    alias /static/admin/;
  }
  
  location /static/rest_framework/ {
    alias /static/rest_framework/;
  }

  # Статика фронтенда - ищем в /static/static/
  location /static/ {
    alias /static/static/;
  }

  # Фронтенд - index.html в корне /static/
  location / {
    root /static;
    try_files $uri $uri /index.html;
  }
}
